### ISSUE TITLE
AttributeError: 'DicomDir' object has no attribute 'DirectoryRecordSequence'

### ISSUE THREAD

**Issue by ryo-39** [RIKEN-BCIL/BCILDCMCONVERT#14]
ATRの林です。お世話になっております。
SiemensのT1dicomの画像ファイルを処理しようとして、
AttributeError: 'DicomDir' object has no attribute 'DirectoryRecordSequence'
というエラーになるデータがあります。
エラーにならないものもあります（ATRのPrismaの撮像データでは処理が出来まして、昔に撮像したTrioで出ました）。
エラーが起こるサンプルのデータは以下にアップしております(適当なタイミングで消させていただきますね)。
https://drive.google.com/file/d/1p7sm2R7JktRkKBFJX_p4Ke754BDwOJ3y
===
Traceback (most recent call last):
  File "/home/foo/BCILDCMCONVERT/miniconda/miniconda/bin/bcil_dcm_convert.py", line 373, in <module>
    bc.main()
  File "/home/foo/BCILDCMCONVERT/miniconda/miniconda/bin/bcil_dcm_convert.py", line 137, in main
    h = self.read_dicom_headers(file_list)
  File "/home/foo/BCILDCMCONVERT/miniconda/miniconda/bin/bcil_dcm_convert.py", line 185, in read_dicom_headers
    ds = pydicom.read_file(file)
  File "/home/foo/BCILDCMCONVERT/miniconda/miniconda/lib/python3.8/site-packages/pydicom/filereader.py", line 887, in dcmread
    dataset = read_partial(fp, stop_when, defer_size=defer_size,
  File "/home/foo/BCILDCMCONVERT/miniconda/miniconda/lib/python3.8/site-packages/pydicom/filereader.py", line 766, in read_partial
    new_dataset = dataset_class(fileobj, dataset, preamble, file_meta_dataset,
  File "/home/foo/BCILDCMCONVERT/miniconda/miniconda/lib/python3.8/site-packages/pydicom/dicomdir.py", line 91, in __init__
    self.parse_records()
  File "/home/foo/BCILDCMCONVERT/miniconda/miniconda/lib/python3.8/site-packages/pydicom/dicomdir.py", line 117, in parse_records
    records = self.DirectoryRecordSequence
  File "/home/foo/BCILDCMCONVERT/miniconda/miniconda/lib/python3.8/site-packages/pydicom/dataset.py", line 835, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DicomDir' object has no attribute 'DirectoryRecordSequence'
===
これは、調べたところによりますと、pydicomの出力するエラーのようです(#9)。
https://github.com/pydicom/pydicom/issues/9

pydicomのリリースノートを見たところ、
この問題点#9は、pydicom v2.1.0にて解消されたようで、
https://pydicom.github.io/pydicom/dev/release_notes/index.html
- Implemented full support (loading, accessing, modifying, writing) of DICOM File-sets and their DICOMDIR files via the FileSet class (#9, #243, #1093)
pydicomのバージョンを最新の2.2.0にバージョンアップして試したのですが、同じエラーが発生します。
もしかすると、BCILDCMCONVERTの問題ではないのかもしれませんが、
ご報告させていただきました。もしお時間がありましたらご覧いただけますと幸いです。

**Comment by takuya-hayashi** [comment]
良輔さん
いつもありがとうございます！こちらでも再現しているようです。こちらのpydicomが2.0のままなので2.1にアップして再現するかどうか確認します（こちらのシステム上2.2までは上げられないようです）。
いまのところbcildcmconvert側の問題ではなさそうなのですが、もう少し調査進め、何等かの回避策をとれないかも含め考えてみます。ありがとうございました。また連携します。
林


2021年1月15日(金) 14:25 ryo-39 <notifications@github.com>:
